### ISSUE TITLE
Invalid Data

### ISSUE THREAD

**Issue by bbroge** [Chaosvex/Halo-Status#2]
This doesn't work with Halo plugin SAPP. I don't understand why because other web based stats work with any version of halo as far as I can tell. Does this handle the query flags differently?

Thanks.

**Comment by erm3nda** [comment]
Sounds a bit logical. If the SAPP plugin does or handle the server data in a different way, the script would not work. Did u double checked it in different servers?

**Comment by Chaosvex** [comment]
The script did some sanity checking that was rendered useless by SAPP's query string modifications. All should be fine now.

Better late than never, right? ;)
