### ISSUE TITLE
Error un http responses - configuration

### ISSUE THREAD

**Issue by crisaldev** [Chaosvex/Halo-Status#4]
Hi, I love your script, but I have not been able to get it to work either locally on my PC or in my hosting because it always comes with an http error, I used the changes you described in the script in the ajax section but never I've been able to make it work, I do not know if it's a bug but that's why I put it here to get some help.

Thank you

**Comment by Chaosvex** [comment]
What error are you receiving?

**Comment by crisaldev** [comment]
whenever I try to perform the query of a server, the following message "An HTTP error occured. Retrying" and when I change the ajax.php as it says in the readme.txt always the same message but in a more continuous way

**Comment by Chaosvex** [comment]
Try changing the line at https://github.com/Chaosvex/Halo-Status/blob/master/js/query.js#L71 from:
```js
that._status.error = "An HTTP error occured";
``` 
to 
```js
that._status.error = "Error: " + status + " - " + error;
```

Change https://github.com/Chaosvex/Halo-Status/blob/master/js/query.js#L70 from:
```js
error: function (msg) {
```
to 
```js
error: function(xhr, status, error) {
```

**Comment by crisaldev** [comment]
thanks, with that it works already but in a random way 2 errors come out, one is: "invalidez data received, retrying..." but the query show the actual status of the server, and the second one is: "An HTTP error ocurred, Retrying" and this is very weird to happen but I think it is better that it works so that it does not work and another question, how can I get the variables from the server to be able to show if it is a sapp server, which version of sapp is and if it has active the ac thanks

**Comment by EffakT** [comment]
@CristianQuintero Not sure if you still need help, the issue for me was due to me using php7.
PHP7 does not allow you to supply "NULL" as a parameter on the socket_select() function. Setting a $null = NULL variable, fixed the issue for me. (Line 186 on QueryServer.class.php) changed to
`$null = null;
$changed = socket_select($read, $null, $null, $this->timeout);`

**Comment by crisaldev** [comment]
@EffakT Hi, I'm sorry for my answer so late, but in my case I do not use PHP7, the versions that I usually use are PHP5.4, 5.5 and 5.6, anyway, thanks for the comment for when I should use PHP7, I'll keep it in mind

**Comment by Chaosvex** [comment]
@CristianQuintero Although it was updated to be compatible with SAPP servers, it doesn't support displaying the custom SAPP data simply because it predates that data. If there's interest, I might be able add it.

Apologies for the extremely late reply.

**Comment by crisaldev** [comment]
@Chaosvex Don't worry, the important thing is the answer hahahaha, and about the new sapp data, it would be a great idea, since that custom data that sapp uses nowadays allows us to know which map would be the next one and what was the one that happened, so it would help a lot to the users to know which maps could follow in the cycle of the map, to others of also indicate if the server has AC active or not if I'm not wrong that option appears in sapp, or one the same server owner can add that value

**Comment by Chaosvex** [comment]
I'll try to get the SAPP data added soon-ish.
